### ISSUE TITLE
wsse not working?

### ISSUE THREAD

**Issue by e-moe** [8p/GuzzleBundle#10]
Plugin attached by `guzzle.emitter` in GuzzleExtension.php. Is it still available in Guzzle6?

**Comment by florianpreusner** [comment]
[WSSE Plugin](https://github.com/8p/guzzle-wsse-plugin/releases/tag/v2.0.2) is not compatible with Guzzle 6 and has to be changed. That's why it is commented out. Will be fixed soon (hopefully today/tomorrow).

Please use version 2.x to use WSSE.
