### ISSUE TITLE
Params in header

### ISSUE THREAD

**Issue by pasqualepalmaccio** [8p/GuzzleBundle#101]
Hi, i want to set some params in header like api_key or a payload but i'm not able to do it. Is it possible to set in header node ( in config.yml) some params to request headers ?

**Comment by Neirda24** [comment]
@pasqualepalmaccio : I had the same issue. Here is my quick fix: https://packagist.org/packages/neirda24/8p-guzzle-token

**Comment by florianpreusner** [comment]
Issue solved by https://github.com/8p/GuzzleBundle/pull/111
