### ISSUE TITLE
Error parse file services

### ISSUE THREAD

**Issue by luismatesanz** [8p/GuzzleBundle#11]
Unable to parse file "/vendor/eightpoints/guzzle-bundle/EightPoints/Bundle/GuzzleBundle/DependencyInjection/../Resources/config/services.xml".

Element '{http://symfony.com/schema/dic/services}factory': This element is not expected.

I installed it but doesnt work.

Can you help me?

**Comment by luismatesanz** [comment]
Sorry. I have install version symfony 2.3.* and its dont work.

**Comment by florianpreusner** [comment]
You can try to use version 2.x of this bundle to get it running. Maybe this helps.
