### ISSUE TITLE
5.4 BC: `headers` config no longer works

### ISSUE THREAD

**Issue by AlexeyKosov** [8p/GuzzleBundle#112]
The deprecated `headers` config parameter stopped working at all in v5.4 even though it's mentioned in the docs that it will be supported until v6. Now it works only under the `options` section.

**Comment by florianpreusner** [comment]
Hi @AlexeyKosov,

thanks for your info. You are right. It was my mistake to release such a change as a minor version. I removed 5.4 and added the changes to the new release "v6.0". I hope that solves that issue. It would be awesome if you can check that and if everything is back normal again to close that issue.

I apologize for the inconvenience.

**Comment by AlexeyKosov** [comment]
If you have removed the 5.4 version at all, of course, it should solve the issue since everything was working fine in the 5.3
But `composer update` doesn't revert the version back to 5.3 so I can't check it, and moreover, I already got rid of the deprecated config options in my projects to avoid any issues.
Anyway, thanks for the quick fix.
