### ISSUE TITLE
Incorrect return value for promise reject in EventDispatchMiddleware

### ISSUE THREAD

**Issue by TheLevti** [8p/GuzzleBundle#114]
I have noticed that whatever I set for the `http_errors` option for the guzzle client, I still would end up without an exception being thrown when the response has a status code `>= 400`. After going through the handler stack I saw that the `EventDispatchMiddleware` incorrectly returns from the "rejected" function of it's promise.

Returning just the response in the "reject" function will result in invoking the "fulfilled" function of the following handlers. As I understood correctly, this middleware should not modify the response nor catch the reject and thus should propagate the rejection to the next handler.

Secondly the reject reason reason does not necessarily have a response object of type `Psr\Http\Message\ResponseInterface` if the reason or exception is not of type `GuzzleHttp\Exception\RequestException`. Even if the reason is of type `RequestException`, it can still return `null` when calling `getResponse()`. That means a PostTransactionEvent should also accept a `null` value. Not emitting an event only because the response is null does not seem logical to me.

I'm going to make a pull request for this issue.

**Comment by bratok** [comment]
+

**Comment by bratok** [comment]
+1

**Comment by florianpreusner** [comment]
👍  Thanks for this report and the fix!
