### ISSUE TITLE
Attempted to call an undefined method named "send" of class "GuzzleHttp\Psr7\Response"

### ISSUE THREAD

**Issue by smartinsalmeida** [8p/GuzzleBundle#16]
I've updated to symfony 2.7 and PHP to 5.5
Get this error.

What i'm missing ?

**Comment by florianpreusner** [comment]
Hi,

please provide more information:
- which version of this bundle are you using?
- how does your code look like?
- please share your configuration if this bundle

Thanks.

**Comment by smartinsalmeida** [comment]
HI and thanks

"eightpoints/guzzle-bundle": "dev-master"

config.yml

guzzle:
    clients:
        api_wiki:
            base_url: "http://fr.wikipedia.org"

            headers:
                Accept: "application/json"

THE code

 $client   = $this->get('guzzle.client.api_wiki');
 $request = $client->get("/w/api.php?action=query&prop=extracts&exintro=&format=json&continue=&titles=**whatever**");
 $response = $request->send();

This bundle worked fine before guzzle 6 and 5.5 requirement

Thanks

**Comment by florianpreusner** [comment]
Hi,

thanks for adding data.
You don't have to use send() anymore. When using get() a response will be returned directly:

```php
$client = $this->get('guzzle.client.api_wiki');
$response = $client->get('https://api.github.com/user', ['auth' =>  ['user', 'pass']]);
echo $response->getStatusCode();
// "200"
echo $response->getHeader('content-type');
// 'application/json; charset=utf8'
echo $response->getBody();
```

You can find more information in Guzzle documentation: http://docs.guzzlephp.org/en/latest/

Best regards
Florian

**Comment by OM4455** [comment]
BNVBN BVN BNVBNB
