### ISSUE TITLE
Error in RequestHeaderMiddleware if headers are missing

### ISSUE THREAD

**Issue by yvmarques** [8p/GuzzleBundle#19]
Looks like the method getHeaders returns null if you don't set any header in the configuration.

**Comment by florianpreusner** [comment]
Hi,

thanks for your report. Can you verify that the fix is working for you? I'm going to create a new version if everything is fine.

Thanks and best regards
Florian

**Comment by yvmarques** [comment]
Hi,

It works for me :+1: 

-- Yvan
