### ISSUE TITLE
Question: Does your bundle support $client->postAsync() calls?

### ISSUE THREAD

**Issue by thim81** [8p/GuzzleBundle#28]
I'm looking for a Symfony2 bundle that support Async call which is supported by Guzzle.

I tried to use but nothing happens, no error or warning.

**Comment by florianpreusner** [comment]
Please provide more information, so your issue can be checked:

- version of bundle
- code snippet that uses $client->*Async(...
- make sure you have read the [FAQ](http://docs.guzzlephp.org/en/latest/faq.html#can-guzzle-send-asynchronous-requests)

This bundle only provides a integration into symfony. All features of Guzzle are available and should work.
