### ISSUE TITLE
Cannot composer install/update with sf 3.0

### ISSUE THREAD

**Issue by xGouley** [8p/GuzzleBundle#29]
Composer fails installing/updating GuzzleBundle with Symfony 3.0, that seems to brings HttpKernel v3.0 too.

**Comment by xGouley** [comment]
Maybe a requirement like "symfony/whatever": "~2.6|~3.0" could to the trick ?

**Comment by florianpreusner** [comment]
Thanks for this info. Following pull request was merged and should do the trick:
https://github.com/8p/GuzzleBundle/pull/30
