### ISSUE TITLE
Overwritting WssePlugin

### ISSUE THREAD

**Issue by sebastianblum** [8p/GuzzleBundle#34]
Lieber Florian,

ich bin so frei und schreibe direkt auf Deutsch. Aktuell stehe ich vor der Herausforderung, dass eine API, die ich mit WsseToken ansprechen möchte, nur einen MD5 Nonce erlaubt.

Gar kein Problem, dachte ich zumindest, einfach die Klasse WsseAuthMiddleware (https://github.com/8p/guzzle-wsse-middleware/blob/master/src/EightPoints/Guzzle/WsseAuthMiddleware.php) vererben, Methode generateNonce überschreiben und in der Konfiguration meine überschriebene Klasse als Parameter guzzle_bundle.middleware.wsse.class einfügen.

Nur leider funktioniert es nicht wie erwartet, und ich glaube, das Problem liegt genau hier:

    $wsse = new Definition($container->getParameter('guzzle_bundle.middleware.wsse.class'));

https://github.com/8p/GuzzleBundle/blob/master/DependencyInjection/GuzzleExtension.php#L229

Hier wird in meinen Augen der Klassenname direkt aus der Konfiguration eingefügt, nämlich dieser Wert:

    parameter key="guzzle_bundle.middleware.wsse.class">EightPoints\Guzzle\WsseAuthMiddleware</parameter>
https://github.com/8p/GuzzleBundle/blob/master/Resources/config/services.xml#L20

So wie ich das verstehe, müsste hier doch der Parameter weiterhin eingefügt bleiben, damit der noch überschrieben werden kann und erst bei der Erzeugung der Instanzen müssten der Klassenname festgelegt werden oder?

Habe ich einen Denkfehler drin?

vielen Dank für deine Unterstützung,
Sebastian

**Comment by florianpreusner** [comment]
Hi,

wäre vermutlich genauso vorgegangen. Hätte eigentlich auch erwartet, dass es genau so funktioniert.
Deine Änderung behebt aber das Problem. Danke dafür!

Beste Grüße
