### ISSUE TITLE
Can't get Content of the Body using this Bundle

### ISSUE THREAD

**Issue by grzegorztomasiak** [8p/GuzzleBundle#43]
$client = $this->get('guzzle.client.api');
        $response = $client->get('/api/users);
        var_dump($response->getBody()->getContents()); //empty

        $client = new \GuzzleHttp\Client();
        $res = $client->request('GET', 'http://local.project/api/users');
        var_dump($res->getBody()->getContents()); //gives content

If I do request using Guzzle Client it works, but when I use the bundle request it does not work, hoewever in the profiler it works.. what could be the problem?

**Comment by GCalmels** [comment]
Hey, I think it's because you have to deserialize the body :
```php
$client = $this->get('guzzle.client.api');
$response = $client->get('/api/users);
\Doctrine\Common\Util\Debug::dump(json_decode($response->getBody()));
```

It should work!

**Comment by grzegorztomasiak** [comment]
Wow, it really does work :) Thanks man! I think this should be documented somewhere...
