### ISSUE TITLE
Add ability to set createdAt offset for wsse middleware

### ISSUE THREAD

**Issue by mathielen** [8p/GuzzleBundle#45]
Please provide the ability to configure the wsse plugin that is created here: https://github.com/8p/GuzzleBundle/blob/master/DependencyInjection/GuzzleExtension.php#L123

I need a way to set the created-timestamp-offset-expression:
https://github.com/8p/guzzle-wsse-middleware/pull/10

Thanks

**Comment by florianpreusner** [comment]
@mathielen Can you check if the new implementation of given PR (https://github.com/8p/GuzzleBundle/pull/46) is working for you?

**Comment by florianpreusner** [comment]
Merged. New version of GuzzleBundle will be released today/tomorrow.
