### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Rafaelgfirmino** [8p/GuzzleBundle#55]
Hey man.

How can we solve the test that are failing ?

Will we could not remove the 5.5 version of php travis CI , put the composer version > = 5.4 phpunit and replace the deprecated versions of phpunit? .

**Comment by florianpreusner** [comment]
You are right. We should not support PHP 5.5 anymore because it also reached it's End of Life (http://php.net/supported-versions.php). We should also stick to PHPUnit <= 5.4. 👍

**Comment by Rafaelgfirmino** [comment]
Thanks man!
Don’t forget to release a new version because of packagist. 

There are already many commits the front of the version 4.5.1

**Comment by florianpreusner** [comment]
Release v5.0.0 because of BC break.
https://github.com/8p/GuzzleBundle/releases/tag/v5.0.0
