### ISSUE TITLE
Logs are cleared when Exception is shown in development

### ISSUE THREAD

**Issue by siraic** [8p/GuzzleBundle#61]
When an exception occurs in development, a subrequest is made to `twig.controller.exception:showAction` to show the symfony exception page.

This means that a second call is made to `HttpDataCollector::collect`, this function contains the lines:

```
        // clear log to have only messages related to symfony request context
        $this->logger->clear();
```

This means that on the second call, all message will be cleared, and none will show up in in the profiler.

Fixing this might be as simple as removing this line, but I'm not sure how many side-effects it will have.

EDIT: on second thought, it might be better change `setMessages` to `addMessages`.

I'm on Symfony 3.1.4

**Comment by florianpreusner** [comment]
Thanks!
