### ISSUE TITLE
Deprecate PHP 5.x?

### ISSUE THREAD

**Issue by florianpreusner** [8p/GuzzleBundle#96]
I would like to use PHP7 features like type hinting. Therefore we have to require PHP >= 7.
It would be nice to get some feedback here.

PHP Release Process: https://wiki.php.net/rfc/releaseprocess
PHP 5 Active Support Ends: https://thephp.cc/news/2016/12/php-5-active-support-ends-now-what

**Comment by wimme002** [comment]
Since PHP 5.x is EOL since a few days I vote in favor of PHP >=7.
This will be a breaking change so I suggest to create a new major release for the package so users with PHP 5 can still use the old version without problems.

**Comment by florianpreusner** [comment]
Yip, I agree. I would remove PHP 5 support in version 6 (already created a milestone for that). So version 5 (current version) still get some smaller support and will have PHP 5 compatibility.
